apiVersion: v1
kind: Service
metadata:
  name: patient-record-service
spec:
  type: LoadBalancer
  selector:
    app: patient-record-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
